# Generated by Django 5.2.15 on 2026-07-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dyno", models.CharField(max_length=100)),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(max_length=50)),
                ("command", models.TextField()),
                ("job_key", models.CharField(max_length=255)),
                ("job_label", models.CharField(max_length=500)),
                ("group_label", models.CharField(max_length=500)),
                ("args", models.TextField(blank=True)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                ("exit_status", models.IntegerField(blank=True, null=True)),
                ("outcome", models.CharField(max_length=20)),
                ("stopped", models.BooleanField(default=False)),
                ("cycled", models.BooleanField(default=False)),
                ("peak_rss_mb", models.FloatField(blank=True, null=True)),
                ("quota_mb", models.IntegerField(blank=True, null=True)),
                ("mem_pct", models.FloatField(blank=True, null=True)),
                ("peak_load", models.FloatField(blank=True, null=True)),
                ("dyno_size", models.CharField(blank=True, max_length=30, null=True)),
                ("cadence", models.CharField(blank=True, max_length=20)),
                ("mem_series", models.JSONField(blank=True, null=True)),
                ("load_series", models.JSONField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dyno", "start"), name="uniq_run_dyno_start"
                    )
                ],
            },
        ),
    ]
